version: '3.7'
services:
  
  php:
    build:
      context: ./
      dockerfile: Dockerfile-php
    volumes:
      - dokuwiki:/srv/dokuwiki
    restart: always

  web:
    depends_on:
      - php
    build:
      context: ./
      dockerfile: Dockerfile-web
    ports: 
      - 10.0.0.1:8080:80
    volumes:
      - ./dokuwiki-nginx.conf:/etc/nginx/conf.d/default.conf
      - dokuwiki:/srv/dokuwiki
    restart: always

volumes:
  dokuwiki:
